{"payload":{"allShortcutsEnabled":true,"fileTree":{"xmls":{"items":[{"name":"Dog.dtd","path":"xmls/Dog.dtd","contentType":"file"},{"name":"External-Dog.xml","path":"xmls/External-Dog.xml","contentType":"file"},{"name":"External-Owner.xml","path":"xmls/External-Owner.xml","contentType":"file"},{"name":"Owner.dtd","path":"xmls/Owner.dtd","contentType":"file"},{"name":"owner-style.xslt","path":"xmls/owner-style.xslt","contentType":"file"},{"name":"owner.html","path":"xmls/owner.html","contentType":"file"}],"totalCount":6},"":{"items":[{"name":".settings","path":".settings","contentType":"directory"},{"name":"db","path":"db","contentType":"directory"},{"name":"lib","path":"lib","contentType":"directory"},{"name":"src","path":"src","contentType":"directory"},{"name":"xmls","path":"xmls","contentType":"directory"},{"name":".classpath","path":".classpath","contentType":"file"},{"name":".gitignore","path":".gitignore","contentType":"file"},{"name":".project","path":".project","contentType":"file"}],"totalCount":8}},"fileTreeProcessingTime":6.6013720000000005,"foldersToFetch":[],"reducedMotionEnabled":"system","repo":{"id":612300912,"defaultBranch":"master","name":"zooDemo","ownerLogin":"aikaterinikoutsou","currentUserCanPush":true,"isFork":false,"isEmpty":false,"createdAt":"2023-03-10T17:26:02.000+01:00","ownerAvatar":"https://avatars.githubusercontent.com/u/70624913?v=4","public":true,"private":false},"refInfo":{"name":"master","listCacheKey":"v0:1678465749.872247","canEdit":true,"refType":"branch","currentOid":"69884cac743937a5c93a6e96b6a6f52af4cd5325"},"path":"xmls/External-Owner.xml","currentUser":{"id":70624913,"login":"aikaterinikoutsou","userEmail":"aikaterini.koutsou@ceu.es"},"blob":{"rawBlob":"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n\n<!DOCTYPE Owner [\n\t<!ELEMENT Owner (email, phone, cardNumber, dogs)>\n\t<!ATTLIST Owner name CDATA #REQUIRED>\n\t<!ELEMENT email (#PCDATA)>\n\t<!ELEMENT phone (#PCDATA)>\n\t<!ELEMENT cardNumber (#PCDATA)>\n\t<!ELEMENT dogs (dog+)>\n\t<!ELEMENT dog (breed,coat, dob, cured, owner)>\n\t<!ATTLIST dog name CDATA #REQUIRED>\n\t\t<!ELEMENT breed (#PCDATA)>\n\t\t<!ELEMENT coat (#PCDATA)>\n\t\t<!ELEMENT dob (#PCDATA)>\n\t\t<!ELEMENT cured (#PCDATA)>\n\t\t<!ELEMENT owner (#PCDATA)>\n]>\n\n\n<Owner name= \"Mario\">\n\t<email> aikaterini.koutsou@ceu.es </email>\n\t<phone> 15050 </phone>\n\t<cardNumber> 56898231659596 </cardNumber>\n\t<dogs>\n\t\t<dog name= \"Max\">\n\t\t\t<breed> Doberman </breed>\n\t\t\t<coat>black</coat>\n\t\t\t<dob>2016-12-21</dob>\n\t\t\t<cured>1</cured>\n\t\t\t<owner>1</owner>\n\t\t</dog>\n\t\t<dog name= \"Sunshine\">\n\t\t\t<breed> labrador </breed>\n\t\t\t<coat>brown</coat>\n\t\t\t<dob>2010-08-13</dob>\n\t\t\t<cured>0</cured>\n\t\t\t<owner>1</owner>\n\t\t</dog>\n\t</dogs>\t\n</Owner>\n\t","colorizedLines":null,"stylingDirectives":[[{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":13,"cssClass":"pl-e"},{"start":14,"end":19,"cssClass":"pl-s"},{"start":14,"end":15,"cssClass":"pl-pds"},{"start":18,"end":19,"cssClass":"pl-pds"},{"start":19,"end":28,"cssClass":"pl-e"},{"start":29,"end":36,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-pds"},{"start":35,"end":36,"cssClass":"pl-pds"},{"start":36,"end":47,"cssClass":"pl-e"},{"start":48,"end":53,"cssClass":"pl-s"},{"start":48,"end":49,"cssClass":"pl-pds"},{"start":52,"end":53,"cssClass":"pl-pds"}],[],[{"start":2,"end":9,"cssClass":"pl-ent"},{"start":10,"end":15,"cssClass":"pl-e"}],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[{"start":1,"end":6,"cssClass":"pl-ent"},{"start":7,"end":11,"cssClass":"pl-e"},{"start":13,"end":20,"cssClass":"pl-s"},{"start":13,"end":14,"cssClass":"pl-pds"},{"start":19,"end":20,"cssClass":"pl-pds"}],[{"start":2,"end":7,"cssClass":"pl-ent"},{"start":37,"end":42,"cssClass":"pl-ent"}],[{"start":2,"end":7,"cssClass":"pl-ent"},{"start":17,"end":22,"cssClass":"pl-ent"}],[{"start":2,"end":12,"cssClass":"pl-ent"},{"start":31,"end":41,"cssClass":"pl-ent"}],[{"start":2,"end":6,"cssClass":"pl-ent"}],[{"start":3,"end":6,"cssClass":"pl-ent"},{"start":7,"end":11,"cssClass":"pl-e"},{"start":13,"end":18,"cssClass":"pl-s"},{"start":13,"end":14,"cssClass":"pl-pds"},{"start":17,"end":18,"cssClass":"pl-pds"}],[{"start":4,"end":9,"cssClass":"pl-ent"},{"start":22,"end":27,"cssClass":"pl-ent"}],[{"start":4,"end":8,"cssClass":"pl-ent"},{"start":16,"end":20,"cssClass":"pl-ent"}],[{"start":4,"end":7,"cssClass":"pl-ent"},{"start":20,"end":23,"cssClass":"pl-ent"}],[{"start":4,"end":9,"cssClass":"pl-ent"},{"start":13,"end":18,"cssClass":"pl-ent"}],[{"start":4,"end":9,"cssClass":"pl-ent"},{"start":13,"end":18,"cssClass":"pl-ent"}],[{"start":4,"end":7,"cssClass":"pl-ent"}],[{"start":3,"end":6,"cssClass":"pl-ent"},{"start":7,"end":11,"cssClass":"pl-e"},{"start":13,"end":23,"cssClass":"pl-s"},{"start":13,"end":14,"cssClass":"pl-pds"},{"start":22,"end":23,"cssClass":"pl-pds"}],[{"start":4,"end":9,"cssClass":"pl-ent"},{"start":22,"end":27,"cssClass":"pl-ent"}],[{"start":4,"end":8,"cssClass":"pl-ent"},{"start":16,"end":20,"cssClass":"pl-ent"}],[{"start":4,"end":7,"cssClass":"pl-ent"},{"start":20,"end":23,"cssClass":"pl-ent"}],[{"start":4,"end":9,"cssClass":"pl-ent"},{"start":13,"end":18,"cssClass":"pl-ent"}],[{"start":4,"end":9,"cssClass":"pl-ent"},{"start":13,"end":18,"cssClass":"pl-ent"}],[{"start":4,"end":7,"cssClass":"pl-ent"}],[{"start":3,"end":7,"cssClass":"pl-ent"}],[{"start":2,"end":7,"cssClass":"pl-ent"}],[]],"csv":null,"csvError":null,"dependabotInfo":{"showConfigurationBanner":null,"configFilePath":null,"networkDependabotPath":"/aikaterinikoutsou/zooDemo/network/updates","dismissConfigurationNoticePath":"/settings/dismiss-notice/dependabot_configuration_notice","configurationNoticeDismissed":false,"repoAlertsPath":"/aikaterinikoutsou/zooDemo/security/dependabot","repoSecurityAndAnalysisPath":"/aikaterinikoutsou/zooDemo/settings/security_analysis","repoOwnerIsOrg":false,"currentUserCanAdminRepo":true},"displayName":"External-Owner.xml","displayUrl":"https://github.com/aikaterinikoutsou/zooDemo/blob/master/xmls/External-Owner.xml?raw=true","headerInfo":{"blobSize":"966 Bytes","deleteInfo":{"deletePath":"https://github.com/aikaterinikoutsou/zooDemo/delete/master/xmls/External-Owner.xml","deleteTooltip":"Delete this file"},"editInfo":{"editTooltip":"Edit this file"},"ghDesktopPath":"x-github-client://openRepo/https://github.com/aikaterinikoutsou/zooDemo?branch=master&filepath=xmls%2FExternal-Owner.xml","gitLfsPath":null,"onBranch":true,"shortPath":"86eb347","siteNavLoginPath":"/login?return_to=https%3A%2F%2Fgithub.com%2Faikaterinikoutsou%2FzooDemo%2Fblob%2Fmaster%2Fxmls%2FExternal-Owner.xml","isCSV":false,"isRichtext":false,"toc":null,"lineInfo":{"truncatedLoc":"41","truncatedSloc":"37"},"mode":"file"},"image":false,"isCodeownersFile":null,"isValidLegacyIssueTemplate":false,"issueTemplateHelpUrl":"https://docs.github.com/articles/about-issue-and-pull-request-templates","issueTemplate":null,"discussionTemplate":null,"language":"XML","large":false,"loggedIn":true,"newDiscussionPath":"/aikaterinikoutsou/zooDemo/discussions/new","newIssuePath":"/aikaterinikoutsou/zooDemo/issues/new","planSupportInfo":{"repoIsFork":null,"repoOwnedByCurrentUser":null,"requestFullPath":"/aikaterinikoutsou/zooDemo/blob/master/xmls/External-Owner.xml","showFreeOrgGatedFeatureMessage":null,"showPlanSupportBanner":null,"upgradeDataAttributes":null,"upgradePath":null},"publishBannersInfo":{"dismissActionNoticePath":"/settings/dismiss-notice/publish_action_from_dockerfile","dismissStackNoticePath":"/settings/dismiss-notice/publish_stack_from_file","releasePath":"/aikaterinikoutsou/zooDemo/releases/new?marketplace=true","showPublishActionBanner":false,"showPublishStackBanner":false},"renderImageOrRaw":false,"richText":null,"renderedFileInfo":null,"tabSize":8,"topBannersInfo":{"overridingGlobalFundingFile":false,"globalPreferredFundingPath":null,"repoOwner":"aikaterinikoutsou","repoName":"zooDemo","showInvalidCitationWarning":false,"citationHelpUrl":"https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files","showDependabotConfigurationBanner":null,"actionsOnboardingTip":null},"truncated":false,"viewable":true,"workflowRedirectUrl":null,"symbols":{"timedOut":false,"notAnalyzed":true,"symbols":[]}},"csrf_tokens":{"/aikaterinikoutsou/zooDemo/branches":{"post":"ZkUe-HsyMOdmdXfXS7dS_faiWpysc7XzvP17aSuKgu4pALfhOJ1gH4TwgKtX6abypPwYoLBxFs4G9qS-AbuHpQ"}}},"title":"zooDemo/External-Owner.xml at master Â· aikaterinikoutsou/zooDemo","locale":"en"}